models/topic.py
from models import Model
from models.user import User
from models.reply import Reply
from models.board import Board

class Topic(Model):
    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            ('views', int, 0),
            ('title', str, ''),
            ('content', str, ''),
            ('user_id', str, 0),
            ('board_id', str, 0),
        ]
        return names

    @classmethod
    def find(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        ms = Reply.all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.one(id=self.board_id)
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    @classmethod
    def recent_topic(cls, id):
        ms = Topic.all(user_id=id)
        number = 5
        if len(ms) < number:
            recent_topic = reversed(ms)
        else:
            recent_topic = reversed(ms[-number:])
        return recent_topic

    @classmethod
    def recent_reply(cls, id):
        ms = Reply.all(user_id=id)
        recent_reply = []
        number = 5
        if len(ms) < number:
            ms = reversed(ms)
        else:
            ms = reversed(ms[-number:])
        for m in ms:
            t = Topic.one(id=m.topic_id)
            if t is not None:
                recent_reply.append(t)
        return recent_reply

routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)
from werkzeug.utils import secure_filename
from models.user import User
from models.topic import Topic
import os
import uuid

from routes import current_user,new_csrf_token
from utils import log

main = Blueprint('index', __name__)


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login u', u)
    if u is None:
        # 转到 topic.index 页面
        # return redirect(url_for('topic.index'))
        return redirect(url_for('index.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        print('login', session)
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        # abort(404)
        return redirect(url_for('.index'))
    else:
        board_id = int(request.args.get('board_id', -1))
        recent_topics = Topic.recent_topic(u.id)
        recent_replies = Topic.recent_reply(u.id)
        return render_template('profile.html', user=u, bid=board_id,
                               recent_topics=recent_topics, recent_replies=recent_replies)


@main.route('/user/<string:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        # abort(404)
        return redirect(url_for('.index'))
    else:
        board_id = int(request.args.get('board_id', -1))
        recent_topics = Topic.recent_topic(id)
        recent_replies = Topic.recent_reply(id)
        return render_template('profile.html', user=u, bid=board_id,
                               recent_topics=recent_topics, recent_replies=recent_replies)


def valid_suffix(suffix):
    valid_type = ['jpg', 'png', 'jpeg']
    return suffix in valid_type


@main.route('/image/add', methods=["POST"])
def add_img():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    # file 是一个上传的文件对象
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        # 上传的文件一定要用 secure_filename 函数过滤一下名字
        # ../../../../../../../root/.ssh/authorized_keys
        # filename = secure_filename(file.filename)
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        u = current_user()
        User.update(u.id, dict(
            user_image='/uploads/{}'.format(filename)
        ))

    return redirect(url_for(".profile"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory('user_image', filename)


@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    token = new_csrf_token()
    return render_template('setting.html', user=u, token=token)


@main.route('/setting/save', methods=["POST"])
def save_setting():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    form = request.form
    User.update(u.id, form)
    return redirect(url_for(".profile"))


@main.route('/password/save', methods=['POST'])
def save_password():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    form = request.form
    if User.salted_password(form['old_pass']) == u.password:
        new_pass = User.salted_password(str(form.get('new_pass')))
        u.password = new_pass
        u.save()
        return redirect(url_for('.profile'))
    return redirect(url_for('.setting'))


@main.route('/signout', methods=["POST", "GET"])
def signout():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    session.pop("user_id")
    return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *
import json

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    board_id = request.args.get('board_id', 'all')
    if board_id == 'all':
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)

    # if r.exists(board_id):
    #     #log('hit redis')
    #     json_string = r.get(board_id)
    #     json_list = json.loads(json_string)
    # else:
    #     print('not hit redis')
    #     json_list = []
    #     for m in ms:
    #         j = m.json()
    #         j['replies'] = m.replies()
    #         j['user_image'] = m.user().user_image
    #         json_list.append(j)
    #     json_string = json.dumps(json_list)
    #     r.set(board_id, json_string)
    # ms = json_list

    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<string:id>')
def detail(id):
    m = Topic.find(id=id)
    u = User.one(id=m.user_id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, user=u)


@main.route("/add", methods=["POST"])
# @login_required
# @csrf_required
def add():
    form = request.form
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


@main.route("/delete")
# @csrf_required
def delete():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    id = request.args.get('id')
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    board_id = request.args.get('board_id')
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- style -->
    <link rel="stylesheet" href="//o4j806krb.qnssl.com/public/stylesheets/index.min.bdd5dd43.min.css" media="all" />
    <!-- scripts -->
    <script src="//o4j806krb.qnssl.com/public/index.min.aeb155e1.min.js"></script>

    <!--<link rel="stylesheet" href="/static/lib/editor/editor.css">-->
    <!--<link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">-->
    <!--<script src="/static/lib/jquery-3.0.0.min.js"></script>-->
    <!--<script src="/static/lib/markdownit.js"></script>-->
    <!--<script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>-->
    <!--<script src="/static/lib/editor/editor.js"></script>-->
    <!--<script src="/static/lib/editor/ext.js"></script>-->

</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/topic/'>

          <img src="/static/profile/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/topic/'>首页</a></li>

        <li>
            <a href='/mail'>

              未读消息
            </a>
        </li>

        <li><a href='http://python-web-guide.readthedocs.io/zh/latest/'>新手入门</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
{% block main %}{% endblock %}



<div id="backtotop" style="top: 454px; right: 0px;">回到顶部</div>
<div id="footer">
  <div id="footer_main">
    <div class="links">
      <a class="dark" href="https://cnodejs.org/rss">RSS</a>
      |
      <a class="dark" href="https://github.com/cnodejs/nodeclub/">源码地址</a>
    </div>

    <div class="col_fade">

  <p>CNode 社区为国内最专业的 Node.js 开源技术社区，致力于 Node.js 的技术研究。</p>
  <p>服务器赞助商为
    <a href="http://www.ucloud.cn/?utm_source=zanzhu&amp;utm_campaign=cnodejs&amp;utm_medium=display&amp;utm_content=yejiao&amp;ytag=cnodejs_logo" target="_blank" class="sponsor_outlink" data-label="ucloud_bottom">
      <img src="/static/profile/FuIpEaM9bvsZKnQ3QfPtBHWQmLM9" title="ucloud" alt="ucloud" width="92px">
    </a>
  ，存储赞助商为
    <a href="http://www.qiniu.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="qiniu_bottom">
      <img src="/static/profile/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储" alt="七牛云存储" width="115px">
    </a>
  ，由<a href="https://alinode.aliyun.com/?ref=cnode" target="_blank" class="sponsor_outlink" data-label="alinode_bottom">
      <img src="/static/profile/FpMZk31PDyxkC8yStmMQL4XroaGD" title="alinode" alt="alinode" height="54px" width="166px">
    </a>提供应用性能服务。
  </p>
  <p>新手搭建 Node.js 服务器，推荐使用无需备案的 <a href="https://www.digitalocean.com/?refcode=eba02656eeb3">DigitalOcean(https://www.digitalocean.com/)</a></p>
</div>


  </div>
</div>
<div id="sidebar-mask"></div>


<script>
  // google analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script', "https://www.google-analytics.com/analytics.js",'ga');

  ga('create', 'UA-41753901-5', 'auto');
  ga('send', 'pageview');
</script>



<div style="display:none;">
  <script src="/static/profile/z_stat.php" language="JavaScript"></script><script src="/static/profile/core.php" charset="utf-8" type="text/javascript"></script><a href="http://www.cnzz.com/stat/website.php?web_id=1254020586" target="_blank" title="站长统计">站长统计</a>
</div>




</body>
{% block style %}{% endblock %}
</html>

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}
论坛主页
{% endblock %}
{% block main %}
    <div id="main">
         <div id="sidebar">

  <div class="panel">

    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
  <div>
    <a class="user_avatar" href="{{ url_for('index.user_detail', id=user.id) }}">
      <img src="{{ user.user_image }}" title="{{ user.username }}">
    </a>
    <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', id=user.id) }}">{{ user.username }}</a></span>

    <div class="board clearfix">
      <div class="floor">
        <span class="big">积分: 0 </span>
      </div>
    </div>
    <div class="space clearfix"></div>
    <span class="signature">
        “

            {{ user.signature }}

        ”
    </span>
  </div>
</div>


<script>
  $(document).ready(function () {
    $('.follow_btn').click(function () {
      var $me = $(this);
      var action = $me.attr('action');
      var params = {
        follow_id: '5a43700e9807389a1809f78e',
        _csrf: 'g0HcttNH-c6-MWSb1Scw8trGcR_4DSQJEnfg'
      };
      $.post('/user/' + action, params, function (data) {
        if (data.status === 'success') {
          var $btns = $('.follow_btn');
          if (action === 'follow') {
            $btns.html('取消关注');
            $btns.attr('action', 'un_follow');
          } else {
            $btns.html('加入关注');
            $btns.attr('action', 'follow');
          }
          $btns.toggleClass('btn-success');
        }
      }, 'json');
    });
  });
</script>


    </div>

  </div>


  <div class="panel">
    <div class="inner">
      <a href="/topic/new?board_id={{ bid }}" id="create_topic_btn">
        <span class="span-success">发布话题</span>
      </a>
    </div>
  </div>




<div class="panel">
  <div class="inner ads">



      <a href="http://www.ucloud.cn/site/active/gift.html?utm_source=cnodejs&amp;utm_medium=content_pic_pc&amp;utm_campaign=multicloud&amp;utm_content=gift&amp;ytag=cnodejs" target="_blank" class="banner sponsor_outlink" data-label="ucloud-banner">
        <img src="/static/profile/FgQS-GQDfqwAD_v0NuhyYUOUk5MG">
      </a>


        <div class="sep10"></div>

      <a href="https://alinode.aliyun.com/?ref=cnode" target="_blank" class="banner sponsor_outlink" data-label="alinode">
        <img src="/static/profile/Fn4D6BhOTz1IswvmzeZ1q7QW1ls_">
      </a>

  </div>
</div>







  <div class="panel">
    <div class="header">
      <span class="col_fade">友情社区</span>
    </div>
    <div class="inner">
      <ol class="friendship-community">
        <li>
          <a href="https://ruby-china.org/" target="_blank">
            <img src="/static/profile/ruby-china-20150529.png">
          </a>
        </li>
        <div class="sep10"></div>
        <li>
          <a href="http://golangtc.com/" target="_blank">
            <img src="/static/profile/golangtc-logo.png">
          </a>
        </li>
        <div class="sep10"></div>
        <li>
          <a href="http://phphub.org/" target="_blank">
            <img src="/static/profile/phphub-logo.png">
          </a>
        </li>
        <div class="sep10"></div>
        <li>
          <a href="https://testerhome.com/" target="_blank">
            <img src="/static/profile/FjLUc7IJ2--DqS706etPQ1EGajxK">
          </a>
        </li>
      </ol>
    </div>
  </div>
  <div class="panel">
    <div class="header">
      <span class="col_fade">客户端二维码</span>
    </div>
    <div class="inner cnode-app-download">
      <img width="200" src="/static/profile/FtG0YVgQ6iginiLpf9W4_ShjiLfU">
      <br>
      <a href="https://github.com/soliury/noder-react-native" target="_blank">客户端源码地址</a>
    </div>
  </div>

</div>



        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="/topic"
                       class="topic-tab current-tab">
                        全部
                    </a>

                    {% for b in bs %}
                        <a href="/topic?board_id={{ b.id }}"
                           class="topic-tab current-tab">
                            {{ b.title }}
                        </a>
                    {% endfor %}
                </div>
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                            <div class="cell">
                                <div class="topic_title_wrapper">

                                    <a class="user_avatar pull-left">
                                        <img src="{{ t.user().user_image }}" title="avatar"/>
                                    </a>

                                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                        {{ t.title }}
                                    </a>
                                    <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                    <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                        删除
                                    </a>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();

    </script>
{% endblock %}

templates/topic/new.html
{% extends "topic/base.html" %}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                        <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                    <textarea class='editor' name='content' rows='20'
                                              placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                               value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();
    </script>
{% endblock %}